%clasificacion por planta

planta(higuerilla).
planta(laureola).
planta(regaliz_americano).
planta(nerium_oleander).
planta(cicuta).
planta(toloache).
planta(semilla_luna).
planta(codo_de_fraile).
planta(belladona).
planta(ricino).
planta(aconito_comun).
planta(adelfa).
planta(estramonio).
planta(hierba_de_pordioseros).
planta(tortago).
planta(floripondio).
planta(nueza).
planta(dedalera).
planta(nabo_del_diablo).
planta(sauquillo).
planta(reflessia_arnoldii).
planta(wolffia_arrhiza).
planta(pennatia_baylisiana).
planta(amorphophallus_titanum).
planta(dracaena_cinnabari).
planta(selaginella_lepidophylla).
planta(rosa_de_jerico).
planta(mimosa_sensitiva).
planta(tacca_chantrieri).
planta(andansonia).
planta(cereus_grandiflorus).
planta(hydnora_africana).
planta(clathrus_archeri).
planta(manzanilla).
planta(aloe_vera).
planta(ajo).
planta(eucalipto).
planta(cola_caballo).
planta(hiperico).
planta(jengibre).
planta(tomillo).
planta(lavanda).
planta(tila).
planta(diente_leon).
planta(ginkgo_biloba).
planta(mate).
planta(oregano).
planta(pasiflora).
planta(corteza_de_sauce).
planta(agave).
planta(arandano).
planta(acebo).
planta(flor_de_sauco).

%por toxicidad

toxica(higuerilla).
toxica(laureola).
toxica(regaliz_americano).
toxica(nerum_oleander).
toxica(cicuta).
toxica(toloache).
toxica(semilla_luna).
toxica(codo_de_fraile).
toxica(belladona).
toxica(ricino).
toxica(aconito_comun).
toxica(adelfa).
toxica(estramonio).
toxica(hierba_de_pordioseros).
toxica(tortago).
toxica(floripondio).
toxica(nueza).
toxica(dedalera).
toxica(nabo_del_diablo).
toxica(sauquillo).

%medicinal
medicinal(manzanilla).
medicinal(aloe_vera).
medicinal(ajo).
medicinal(eucalipto).
medicinal(cola_caballo).
medicinal(hiperico).
medicinal(jengibre).
medicinal(tomillo).
medicinal(lavanda).
medicinal(tila).
medicinal(diente_leon).
medicinal(ginkgo_biloba).
medicinal(mate).
medicinal(oregano).
medicinal(pasiflora).
medicinal(corteza_de_sauce).
medicinal(agave).
medicinal(arandano).
medicinal(acebo).
medicinal(flor_de_sauco).

%beneficios medicinales
planta_beneficios(manzanilla,"molestias gastrointestinales").
planta_beneficios(manzanilla,"dolor muscular").
planta_beneficios(manzanilla,"calambres").
planta_beneficios(manzanilla,"cafetaleas").
planta_beneficios(manzanilla,"eczemas").
planta_beneficios(manzanilla,"inflamacion").
planta_beneficios(manzanilla,"sinusitis").
planta_beneficios(manzanilla,"colesterol").
planta_beneficios(aloe_vera,"quemaduras").
planta_beneficios(aloe_vera,"manchas").
planta_beneficios(ajo,"antibiotico").
planta_beneficios(ajo,"anticoagulante").
planta_beneficios(ajo,"antioxidante").
planta_beneficios(eucalipto,"asma").
planta_beneficios(eucalipto,"bronquitis").
planta_beneficios(eucalipto,"gripe").
planta_beneficios(eucalipto,"diabetes").
planta_beneficios(cola_caballo,"cistitis").
planta_beneficios(cola_caballo,"eliminacion de toxinas").
planta_beneficios(hiperico,"antidepresivo").
planta_beneficios(hiperico,"diarrea").
planta_beneficios(hiperico,"vomito").
planta_beneficios(jengibre,"antibacterial").
planta_beneficios(jengibre,"cefaleas").
planta_beneficios(jengibre,"fatiga").
planta_beneficios(jengibre,"vomito").
planta_beneficios(tomillo,"estimila apetito").
planta_beneficios(tomillo,"quemaduras").
planta_beneficios(lavanda,"antidepresivo").
planta_beneficios(lavanda,"circulacion").
planta_beneficios(tila,"antidepresivo").
planta_beneficios(tila,"desitoxicacion").
planta_beneficios(diente_leon,"hepaticos").
planta_beneficios(diente_leon,"renales").
planta_beneficios(diente_leon,"desitoxicacion").
planta_beneficios(ginkgo_biloba,"memoria").
planta_beneficios(ginkgo_biloba,"concentracion").
planta_beneficios(ginkgo_biloba,"antioxidante").
planta_beneficios(ginkgo_biloba,"circulacion").
planta_beneficios(mate,"antioxidante").
planta_beneficios(mate,"memoria").
planta_beneficios(mate,"concentracion").
planta_beneficios(oregano,"antioxidante").
planta_beneficios(oregano,"antibiotico").
planta_beneficios(oregano,"inflamacion").
planta_beneficios(pasiflora,"antidepresivo").
planta_beneficios(pasiflora,"circulacion").
planta_beneficios(pasiflora,"inflamacion").
planta_beneficios(corteza_de_sauce,"inflamacion").
planta_beneficios(corteza_de_sauce,"peso").
planta_beneficios(corteza_de_sauce,"cefalea").
planta_beneficios(agave,"heridas").
planta_beneficios(agave,"colesterol").
planta_beneficios(agave,"trigliceridos").
planta_beneficios(agave,"diabetes").
planta_beneficios(arandano,"antioxidante").
planta_beneficios(arandano,"renal").
planta_beneficios(arandano,"eczemas").
planta_beneficios(arandano,"antibiotico").
planta_beneficios(arandano,"circulacion").
planta_beneficios(arandano,"ulceras").
planta_beneficios(arandano,"diabetes").
planta_beneficios(acebo,"fiebre").
planta_beneficios(acebo,"purgante").
planta_beneficios(acebo,"ictericia").
planta_beneficios(acebo,"antidepresivo").
planta_beneficios(flor_de_sauco,"inflamacion").
planta_beneficios(flor_de_sauco,"purgante").
planta_beneficios(flor_de_sauco,"gripa").
planta_beneficios(flor_de_sauco,"diabetes").
planta_beneficios(flor_de_sauco,"colesterol").

%Zona donde se encuentra

planta_zona(higuerilla,estados_unidos).
planta_zona(higuerilla,mexico).
planta_zona(laureola,gran_bretana).
planta_zona(laureola,argelia).
planta_zona(laureola,marruecos).
planta_zona(laureola,azores).
planta_zona(laureola,mexico).
planta_zona(regaliz_americano,america).
planta_zona(regaliz_americano,africa_tropical).
planta_zona(regaliz_americano,antillas).
planta_zona(regaliz_americano,india).
planta_zona(regaliz_americano,mexico).
planta_zona(nerium_oleander,argentina).
planta_zona(nerium_oleander,uruguay).
planta_zona(nerium_oleander,espana).
planta_zona(nerium_oleander,australia).
planta_zona(nerium_oleander,colombia).
planta_zona(nerium_oleander,venezuela).
planta_zona(nerium_oleander,panama).
planta_zona(nerium_oleander,mexico).
planta_zona(nerium_oleander,america).
planta_zona(nerium_oleander,europa).
planta_zona(nerium_oleander,espana).
planta_zona(cicuta,asia).
planta_zona(cicuta,mexico).
planta_zona(toloache,mexico).
planta_zona(semilla_luna,america).
planta_zona(semilla_luna,mexico).
planta_zona(codo_de_fraile,india).
planta_zona(codo_de_fraile,mexico).
planta_zona(belladona,europa).
planta_zona(belladona,africa).
planta_zona(belladona,asia).
planta_zona(ricino,africa).
planta_zona(aconito_comun,europa).
planta_zona(adelfa,mediterraneo).
planta_zona(estramonio,zonas_calidas_mundo).
planta_zona(hierba_de_pordioseros,europa).
planta_zona(tortago,asia_central).
planta_zona(tortago,china).
planta_zona(floripondio,america).
planta_zona(floripondio,europa).
planta_zona(nueza,europa).
planta_zona(dedalera,espana).
planta_zona(nabo_del_diablo,espana).
planta_zona(sauquillo,espana).
planta_zona(reflessia_arnoldii,indonesia).
planta_zona(wolffia_arrhiza,australia).
planta_zona(pennatia_baylisiana,nueva_zelanda).
planta_zona(amorphophallus_titanum,indonesia).
planta_zona(dracaena_cinnabari,islas_canarias).
planta_zona(selaginella_lepidophylla,america_del_norte).
planta_zona(rosa_de_jerico,arabia).
planta_zona(mimosa_sensitiva,america).
planta_zona(tacca_chantrieri,malasia).
planta_zona(andansonia,madagascar).
planta_zona(cereus_grandiflorus,sudamerica).
planta_zona(hydnora_africana,africa).
planta_zona(clathrus_archeri,australia).
planta_zona(manzanilla,europa).
planta_zona(manzanilla,asia).
planta_zona(manzanilla,america).
planta_zona(aloe_vera,arabia).
planta_zona(aloe_vera,america).
planta_zona(ajo,america).
planta_zona(ajo,asia).
planta_zona(ajo,africa).
planta_zona(eucalipto,nueva_ginea).
planta_zona(eucalipto,america).
planta_zona(eucalipto,europa).
planta_zona(eucalipto,asia).
planta_zona(cola_caballo,europa).
planta_zona(hiperico,europa).
planta_zona(jengibre,asia).
planta_zona(jengibre,america).
planta_zona(jengibre,africa).
planta_zona(jengibre,europa).
planta_zona(tomillo,mediterraneo).
planta_zona(lavanda,espana).
planta_zona(lavanda,bulgaria).
planta_zona(lavanda,argentina).
planta_zona(lavanda,japon).
planta_zona(tila,mexico).
planta_zona(diente_leon,europa).
planta_zona(diente_leon,america).
planta_zona(ginkgo_biloba,japon).
planta_zona(mate,sudamerica).
planta_zona(oregano,america).
planta_zona(oregano,europa).
planta_zona(oregano,asia).
planta_zona(pasiflora,peru).
planta_zona(pasiflora,america).
planta_zona(corteza_de_sauce,america).
planta_zona(agave,mexico).
planta_zona(agave,america).
planta_zona(agave,europa).
planta_zona(arandano,estados_unidos).
planta_zona(arandano,chile).
planta_zona(arandano,canada).
planta_zona(arandano,argentina).
planta_zona(arandano,europa).
planta_zona(acebo,asia).
planta_zona(acebo,europa).
planta_zona(flor_de_sauco,america).

%Reglas
%para saber si una planta es medicinal y toxica.
medicinal_toxica(Planta):-toxica(Planta),medicinal(Planta).

%para saber si hay una planta que cure tu enfermedad en tu pais.
enfermedad_pais(Enfermedad,Pais):-planta_beneficios(X,Enfermedad),planta_zona(X,Pais).

%para saber si una planta toxica pertenece a cierto pais.
toxica_pais(Planta,Pais):-toxica(Planta),planta_zona(Planta,Pais).

%para saber si una planta medicinal pertenece a mi pais.
medicinal_pais(Planta,Pais):-medicinal(Planta),planta_zona(Planta,Pais).

